
x_colors = {
    'Light': {
        'bg' :   '#FFFFFF',
        'card':  '#F0F0F2',
        'txt' :  '#44484B',
        'txt_bold': '#FFFFFF',
        'txt_medium': '#92979B',
        'txt_light': '#D3D7DB',
        'accent': '#D2E5F4',
        'primary' : '#E7F0F5',
        'secondary' : '#13607C',
        'opposite': '#EEEEEE',
        'disabled': '#9B9B9B',
        'line': '#C2C7CB'
    },

    'Dark': {
        'bg' :    '#181C1F',
        'card': '#2D3134',
        'txt' :  '#C6C7CB',
        'txt_bold': '#000000',
        'txt_medium': '#797A7C',
        'txt_light': '#3F3F41',
        'accent': '#374955',
        'primary' : '#222B32',
        'secondary' : '#D2E5F4',
        'opposite': '#222831',
        'disabled': '#9B9B9B',
        'line': '#333333'
    },
    'Colors': {'blue': ['0d47a1',
                        '1565c0',
                        '1976d2',
                        '1e88e5',
                        '2196f3',
                        '4686EE',
                        '64b5f6',
                        '90caf9',
                        'bbdefb',
                        'e3f2fd'],
                'brown': ['35251c',
                        '50372a',
                        '6b4938',
                        '865b46',
                        'a06e54',
                        'b2836c',
                        'c09b87',
                        'd5bcaf',
                        'eaddd7',
                        'f8f4f2'],
                'gray': ['222831',
                        '343a40',
                        '495057',
                        '6c757d',
                        'adb5bd',
                        'ced4da',
                        'dee2e6',
                        'e9ecef',
                        'f8f9fa',
                        'ffffff'],
                'green': ['10451d',
                        '155d27',
                        '1a7431',
                        '208b3a',
                        '25a244',
                        '2dc653',
                        '4ad66d',
                        '6ede8a',
                        '92e6a7',
                        'b7efc5'],
                'orange': ['ff4800',
                        'ff5400',
                        'ff6000',
                        'ff6d00',
                        'ff7900',
                        'ff8500',
                        'ff9100',
                        'ff9e00',
                        'ffaa00',
                        'ffb600'],
                'pink': ['ff0a54',
                        'ff477e',
                        'ff5c8a',
                        'ff7096',
                        'ff85a1',
                        'ff99ac',
                        'fbb1bd',
                        'f9bec7',
                        'f7cad0',
                        'fae0e4'],
                'purple': ['b28dff',
                        'bc98ff',
                        'c5a3ff',
                        'd1b1ff',
                        'd7b8ff',
                        'dcbfff',
                        'e3c7ff',
                        'e9cfff',
                        'f2daff',
                        'fbe4ff'],
                'red': ['aa0000',
                        'bb0000',
                        'cd0000',
                        'de1616',
                        'ef2b2b',
                        'ec4040',
                        'e95555',
                        'e56b6b',
                        'e28080',
                        'eaa8a8'],
                'turqo': ['03045e',
                        '023e8a',
                        '0077b6',
                        '0096c7',
                        '00b4d8',
                        '48cae4',
                        '90e0ef',
                        'ade8f4',
                        'caf0f8'],
                'yellow': ['cc9c00',
                        'e0ac00',
                        'f5bc00',
                        'ffc60a',
                        'ffcb1f',
                        'ffcf33',
                        'ffd447',
                        'ffd95c',
                        'ffde70',
                        'ffe285']}

}
